//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

Executor = {};
//HELPER FUNCTIONS AND STRUCTURES

ExecutorService_getBlacklist_args = function (args) {
	this.language = null;
	if (args) {
		if (args.language !== undefined && args.language !== null) {
			this.language = args.language;
		}
	}
};
ExecutorService_getBlacklist_args.prototype = {};
ExecutorService_getBlacklist_args.prototype.read = function (input) {
	input.readStructBegin();
	while (true) {
		var ret = input.readFieldBegin();
		var fname = ret.fname;
		var ftype = ret.ftype;
		var fid = ret.fid;
		if (ftype == Thrift.Type.STOP) {
			break;
		}
		switch (fid) {
			case 1:
				if (ftype == Thrift.Type.STRING) {
					this.language = input.readString();
				} else {
					input.skip(ftype);
				}
				break;
			case 0:
				input.skip(ftype);
				break;
			default:
				input.skip(ftype);
		}
		input.readFieldEnd();
	}
	input.readStructEnd();
	return;
};

ExecutorService_getBlacklist_args.prototype.write = function (output) {
	output.writeStructBegin('ExecutorService_getBlacklist_args');
	if (this.language !== null && this.language !== undefined) {
		output.writeFieldBegin('language', Thrift.Type.STRING, 1);
		output.writeString(this.language);
		output.writeFieldEnd();
	}
	output.writeFieldStop();
	output.writeStructEnd();
	return;
};

ExecutorService_getBlacklist_result = function (args) {
	this.success = null;
	if (args) {
		if (args.success !== undefined && args.success !== null) {
			this.success = Thrift.copyList(args.success, [null]);
		}
	}
};
ExecutorService_getBlacklist_result.prototype = {};
ExecutorService_getBlacklist_result.prototype.read = function (input) {
	input.readStructBegin();
	while (true) {
		var ret = input.readFieldBegin();
		var fname = ret.fname;
		var ftype = ret.ftype;
		var fid = ret.fid;
		if (ftype == Thrift.Type.STOP) {
			break;
		}
		switch (fid) {
			case 0:
				if (ftype == Thrift.Type.LIST) {
					var _size48 = 0;
					var _rtmp352;
					this.success = [];
					var _etype51 = 0;
					_rtmp352 = input.readListBegin();
					_etype51 = _rtmp352.etype;
					_size48 = _rtmp352.size;
					for (var _i53 = 0; _i53 < _size48; ++_i53) {
						var elem54 = null;
						elem54 = input.readString();
						this.success.push(elem54);
					}
					input.readListEnd();
				} else {
					input.skip(ftype);
				}
				break;
			case 0:
				input.skip(ftype);
				break;
			default:
				input.skip(ftype);
		}
		input.readFieldEnd();
	}
	input.readStructEnd();
	return;
};

ExecutorService_getBlacklist_result.prototype.write = function (output) {
	output.writeStructBegin('ExecutorService_getBlacklist_result');
	if (this.success !== null && this.success !== undefined) {
		output.writeFieldBegin('success', Thrift.Type.LIST, 0);
		output.writeListBegin(Thrift.Type.STRING, this.success.length);
		for (var iter55 in this.success) {
			if (this.success.hasOwnProperty(iter55)) {
				iter55 = this.success[iter55];
				output.writeString(iter55);
			}
		}
		output.writeListEnd();
		output.writeFieldEnd();
	}
	output.writeFieldStop();
	output.writeStructEnd();
	return;
};

ExecutorService_getFragment_args = function (args) {
	this.language = null;
	this.functions = null;
	if (args) {
		if (args.language !== undefined && args.language !== null) {
			this.language = args.language;
		}
		if (args.functions !== undefined && args.functions !== null) {
			this.functions = Thrift.copyList(args.functions, [ttypes.FunctionSignature]);
		}
	}
};
ExecutorService_getFragment_args.prototype = {};
ExecutorService_getFragment_args.prototype.read = function (input) {
	input.readStructBegin();
	while (true) {
		var ret = input.readFieldBegin();
		var fname = ret.fname;
		var ftype = ret.ftype;
		var fid = ret.fid;
		if (ftype == Thrift.Type.STOP) {
			break;
		}
		switch (fid) {
			case 1:
				if (ftype == Thrift.Type.STRING) {
					this.language = input.readString();
				} else {
					input.skip(ftype);
				}
				break;
			case 3:
				if (ftype == Thrift.Type.LIST) {
					var _size56 = 0;
					var _rtmp360;
					this.functions = [];
					var _etype59 = 0;
					_rtmp360 = input.readListBegin();
					_etype59 = _rtmp360.etype;
					_size56 = _rtmp360.size;
					for (var _i61 = 0; _i61 < _size56; ++_i61) {
						var elem62 = null;
						elem62 = new ttypes.FunctionSignature();
						elem62.read(input);
						this.functions.push(elem62);
					}
					input.readListEnd();
				} else {
					input.skip(ftype);
				}
				break;
			default:
				input.skip(ftype);
		}
		input.readFieldEnd();
	}
	input.readStructEnd();
	return;
};

ExecutorService_getFragment_args.prototype.write = function (output) {
	output.writeStructBegin('ExecutorService_getFragment_args');
	if (this.language !== null && this.language !== undefined) {
		output.writeFieldBegin('language', Thrift.Type.STRING, 1);
		output.writeString(this.language);
		output.writeFieldEnd();
	}
	if (this.functions !== null && this.functions !== undefined) {
		output.writeFieldBegin('functions', Thrift.Type.LIST, 3);
		output.writeListBegin(Thrift.Type.STRUCT, this.functions.length);
		for (var iter63 in this.functions) {
			if (this.functions.hasOwnProperty(iter63)) {
				iter63 = this.functions[iter63];
				iter63.write(output);
			}
		}
		output.writeListEnd();
		output.writeFieldEnd();
	}
	output.writeFieldStop();
	output.writeStructEnd();
	return;
};

ExecutorService_getFragment_result = function (args) {
	this.success = null;
	if (args) {
		if (args.success !== undefined && args.success !== null) {
			this.success = args.success;
		}
	}
};
ExecutorService_getFragment_result.prototype = {};
ExecutorService_getFragment_result.prototype.read = function (input) {
	input.readStructBegin();
	while (true) {
		var ret = input.readFieldBegin();
		var fname = ret.fname;
		var ftype = ret.ftype;
		var fid = ret.fid;
		if (ftype == Thrift.Type.STOP) {
			break;
		}
		switch (fid) {
			case 0:
				if (ftype == Thrift.Type.STRING) {
					this.success = input.readString();
				} else {
					input.skip(ftype);
				}
				break;
			case 0:
				input.skip(ftype);
				break;
			default:
				input.skip(ftype);
		}
		input.readFieldEnd();
	}
	input.readStructEnd();
	return;
};

ExecutorService_getFragment_result.prototype.write = function (output) {
	output.writeStructBegin('ExecutorService_getFragment_result');
	if (this.success !== null && this.success !== undefined) {
		output.writeFieldBegin('success', Thrift.Type.STRING, 0);
		output.writeString(this.success);
		output.writeFieldEnd();
	}
	output.writeFieldStop();
	output.writeStructEnd();
	return;
};

ExecutorService_execute_args = function (args) {
	this.language = null;
	this.fragment = null;
	this.functions = null;
	this.testCases = null;
	if (args) {
		if (args.language !== undefined && args.language !== null) {
			this.language = args.language;
		}
		if (args.fragment !== undefined && args.fragment !== null) {
			this.fragment = args.fragment;
		}
		if (args.functions !== undefined && args.functions !== null) {
			this.functions = Thrift.copyList(args.functions, [ttypes.FunctionSignature]);
		}
		if (args.testCases !== undefined && args.testCases !== null) {
			this.testCases = Thrift.copyList(args.testCases, [ttypes.TestCase]);
		}
	}
};
ExecutorService_execute_args.prototype = {};
ExecutorService_execute_args.prototype.read = function (input) {
	input.readStructBegin();
	while (true) {
		var ret = input.readFieldBegin();
		var fname = ret.fname;
		var ftype = ret.ftype;
		var fid = ret.fid;
		if (ftype == Thrift.Type.STOP) {
			break;
		}
		switch (fid) {
			case 1:
				if (ftype == Thrift.Type.STRING) {
					this.language = input.readString();
				} else {
					input.skip(ftype);
				}
				break;
			case 2:
				if (ftype == Thrift.Type.STRING) {
					this.fragment = input.readString();
				} else {
					input.skip(ftype);
				}
				break;
			case 3:
				if (ftype == Thrift.Type.LIST) {
					var _size64 = 0;
					var _rtmp368;
					this.functions = [];
					var _etype67 = 0;
					_rtmp368 = input.readListBegin();
					_etype67 = _rtmp368.etype;
					_size64 = _rtmp368.size;
					for (var _i69 = 0; _i69 < _size64; ++_i69) {
						var elem70 = null;
						elem70 = new ttypes.FunctionSignature();
						elem70.read(input);
						this.functions.push(elem70);
					}
					input.readListEnd();
				} else {
					input.skip(ftype);
				}
				break;
			case 4:
				if (ftype == Thrift.Type.LIST) {
					var _size71 = 0;
					var _rtmp375;
					this.testCases = [];
					var _etype74 = 0;
					_rtmp375 = input.readListBegin();
					_etype74 = _rtmp375.etype;
					_size71 = _rtmp375.size;
					for (var _i76 = 0; _i76 < _size71; ++_i76) {
						var elem77 = null;
						elem77 = new ttypes.TestCase();
						elem77.read(input);
						this.testCases.push(elem77);
					}
					input.readListEnd();
				} else {
					input.skip(ftype);
				}
				break;
			default:
				input.skip(ftype);
		}
		input.readFieldEnd();
	}
	input.readStructEnd();
	return;
};

ExecutorService_execute_args.prototype.write = function (output) {
	output.writeStructBegin('ExecutorService_execute_args');
	if (this.language !== null && this.language !== undefined) {
		output.writeFieldBegin('language', Thrift.Type.STRING, 1);
		output.writeString(this.language);
		output.writeFieldEnd();
	}
	if (this.fragment !== null && this.fragment !== undefined) {
		output.writeFieldBegin('fragment', Thrift.Type.STRING, 2);
		output.writeString(this.fragment);
		output.writeFieldEnd();
	}
	if (this.functions !== null && this.functions !== undefined) {
		output.writeFieldBegin('functions', Thrift.Type.LIST, 3);
		output.writeListBegin(Thrift.Type.STRUCT, this.functions.length);
		for (var iter78 in this.functions) {
			if (this.functions.hasOwnProperty(iter78)) {
				iter78 = this.functions[iter78];
				iter78.write(output);
			}
		}
		output.writeListEnd();
		output.writeFieldEnd();
	}
	if (this.testCases !== null && this.testCases !== undefined) {
		output.writeFieldBegin('testCases', Thrift.Type.LIST, 4);
		output.writeListBegin(Thrift.Type.STRUCT, this.testCases.length);
		for (var iter79 in this.testCases) {
			if (this.testCases.hasOwnProperty(iter79)) {
				iter79 = this.testCases[iter79];
				iter79.write(output);
			}
		}
		output.writeListEnd();
		output.writeFieldEnd();
	}
	output.writeFieldStop();
	output.writeStructEnd();
	return;
};

ExecutorService_execute_result = function (args) {
	this.success = null;
	if (args) {
		if (args.success !== undefined && args.success !== null) {
			this.success = Thrift.copyList(args.success, [ttypes.Result]);
		}
	}
};
ExecutorService_execute_result.prototype = {};
ExecutorService_execute_result.prototype.read = function (input) {
	input.readStructBegin();
	while (true) {
		var ret = input.readFieldBegin();
		var fname = ret.fname;
		var ftype = ret.ftype;
		var fid = ret.fid;
		if (ftype == Thrift.Type.STOP) {
			break;
		}
		switch (fid) {
			case 0:
				if (ftype == Thrift.Type.LIST) {
					var _size80 = 0;
					var _rtmp384;
					this.success = [];
					var _etype83 = 0;
					_rtmp384 = input.readListBegin();
					_etype83 = _rtmp384.etype;
					_size80 = _rtmp384.size;
					for (var _i85 = 0; _i85 < _size80; ++_i85) {
						var elem86 = null;
						elem86 = new ttypes.Result();
						elem86.read(input);
						this.success.push(elem86);
					}
					input.readListEnd();
				} else {
					input.skip(ftype);
				}
				break;
			case 0:
				input.skip(ftype);
				break;
			default:
				input.skip(ftype);
		}
		input.readFieldEnd();
	}
	input.readStructEnd();
	return;
};

ExecutorService_execute_result.prototype.write = function (output) {
	output.writeStructBegin('ExecutorService_execute_result');
	if (this.success !== null && this.success !== undefined) {
		output.writeFieldBegin('success', Thrift.Type.LIST, 0);
		output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
		for (var iter87 in this.success) {
			if (this.success.hasOwnProperty(iter87)) {
				iter87 = this.success[iter87];
				iter87.write(output);
			}
		}
		output.writeListEnd();
		output.writeFieldEnd();
	}
	output.writeFieldStop();
	output.writeStructEnd();
	return;
};

ExecutorServiceClient = Executor.Client = function (output, pClass) {
	this.output = output;
	this.pClass = pClass;
	this._seqid = 0;
	this._reqs = {};
};
ExecutorServiceClient.prototype = {};
ExecutorServiceClient.prototype.seqid = function () {
	return this._seqid;
}
ExecutorServiceClient.prototype.new_seqid = function () {
	return this._seqid += 1;
}
ExecutorServiceClient.prototype.getBlacklist = function (language, callback) {
	this._seqid = this.new_seqid();
	if (callback === undefined) {
		var _defer = Q.defer();
		this._reqs[this.seqid()] = function (error, result) {
			if (error) {
				_defer.reject(error);
			} else {
				_defer.resolve(result);
			}
		};
		this.send_getBlacklist(language);
		return _defer.promise;
	} else {
		this._reqs[this.seqid()] = callback;
		this.send_getBlacklist(language);
	}
};

ExecutorServiceClient.prototype.send_getBlacklist = function (language) {
	var output = new this.pClass(this.output);
	output.writeMessageBegin('getBlacklist', Thrift.MessageType.CALL, this.seqid());
	var args = new ExecutorService_getBlacklist_args();
	args.language = language;
	args.write(output);
	output.writeMessageEnd();
	return this.output.flush();
};

ExecutorServiceClient.prototype.recv_getBlacklist = function (input, mtype, rseqid) {
	var callback = this._reqs[rseqid] || function () {
		};
	delete this._reqs[rseqid];
	if (mtype == Thrift.MessageType.EXCEPTION) {
		var x = new Thrift.TApplicationException();
		x.read(input);
		input.readMessageEnd();
		return callback(x);
	}
	var result = new ExecutorService_getBlacklist_result();
	result.read(input);
	input.readMessageEnd();

	if (null !== result.success) {
		return callback(null, result.success);
	}
	return callback('getBlacklist failed: unknown result');
};
ExecutorServiceClient.prototype.getFragment = function (language, functions, callback) {
	this._seqid = this.new_seqid();
	if (callback === undefined) {
		var _defer = Q.defer();
		this._reqs[this.seqid()] = function (error, result) {
			if (error) {
				_defer.reject(error);
			} else {
				_defer.resolve(result);
			}
		};
		this.send_getFragment(language, functions);
		return _defer.promise;
	} else {
		this._reqs[this.seqid()] = callback;
		this.send_getFragment(language, functions);
	}
};

ExecutorServiceClient.prototype.send_getFragment = function (language, functions) {
	var output = new this.pClass(this.output);
	output.writeMessageBegin('getFragment', Thrift.MessageType.CALL, this.seqid());
	var args = new ExecutorService_getFragment_args();
	args.language = language;
	args.functions = functions;
	args.write(output);
	output.writeMessageEnd();
	return this.output.flush();
};

ExecutorServiceClient.prototype.recv_getFragment = function (input, mtype, rseqid) {
	var callback = this._reqs[rseqid] || function () {
		};
	delete this._reqs[rseqid];
	if (mtype == Thrift.MessageType.EXCEPTION) {
		var x = new Thrift.TApplicationException();
		x.read(input);
		input.readMessageEnd();
		return callback(x);
	}
	var result = new ExecutorService_getFragment_result();
	result.read(input);
	input.readMessageEnd();

	if (null !== result.success) {
		return callback(null, result.success);
	}
	return callback('getFragment failed: unknown result');
};
ExecutorServiceClient.prototype.execute = function (language, fragment, functions, testCases, callback) {
	this._seqid = this.new_seqid();
	if (callback === undefined) {
		var _defer = Q.defer();
		this._reqs[this.seqid()] = function (error, result) {
			if (error) {
				_defer.reject(error);
			} else {
				_defer.resolve(result);
			}
		};
		this.send_execute(language, fragment, functions, testCases);
		return _defer.promise;
	} else {
		this._reqs[this.seqid()] = callback;
		this.send_execute(language, fragment, functions, testCases);
	}
};

ExecutorServiceClient.prototype.send_execute = function (language, fragment, functions, testCases) {
	var output = new this.pClass(this.output);
	output.writeMessageBegin('execute', Thrift.MessageType.CALL, this.seqid());
	var args = new ExecutorService_execute_args();
	args.language = language;
	args.fragment = fragment;
	args.functions = functions;
	args.testCases = testCases;
	args.write(output);
	output.writeMessageEnd();
	return this.output.flush();
};

ExecutorServiceClient.prototype.recv_execute = function (input, mtype, rseqid) {
	var callback = this._reqs[rseqid] || function () {
		};
	delete this._reqs[rseqid];
	if (mtype == Thrift.MessageType.EXCEPTION) {
		var x = new Thrift.TApplicationException();
		x.read(input);
		input.readMessageEnd();
		return callback(x);
	}
	var result = new ExecutorService_execute_result();
	result.read(input);
	input.readMessageEnd();

	if (null !== result.success) {
		return callback(null, result.success);
	}
	return callback('execute failed: unknown result');
};
ExecutorServiceProcessor = Executor.Processor = function (handler) {
	this._handler = handler
}
ExecutorServiceProcessor.prototype.process = function (input, output) {
	var r = input.readMessageBegin();
	if (this['process_' + r.fname]) {
		return this['process_' + r.fname].call(this, r.rseqid, input, output);
	} else {
		input.skip(Thrift.Type.STRUCT);
		input.readMessageEnd();
		var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
		output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
		x.write(output);
		output.writeMessageEnd();
		output.flush();
	}
}

ExecutorServiceProcessor.prototype.process_getBlacklist = function (seqid, input, output) {
	var args = new ExecutorService_getBlacklist_args();
	args.read(input);
	input.readMessageEnd();
	if (this._handler.getBlacklist.length === 1) {
		Q.fcall(this._handler.getBlacklist, args.language)
			.then(function (result) {
				var result = new ExecutorService_getBlacklist_result({ success: result });
				output.writeMessageBegin("getBlacklist", Thrift.MessageType.REPLY, seqid);
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			}, function (err) {
				var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
				output.writeMessageBegin("getBlacklist", Thrift.MessageType.EXCEPTION, seqid);
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			});
	} else {
		this._handler.getBlacklist(args.language, function (err, result) {
			if (err == null) {
				var result = new ExecutorService_getBlacklist_result((err != null ? err : { success: result }));
				output.writeMessageBegin("getBlacklist", Thrift.MessageType.REPLY, seqid);
			} else {
				var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
				output.writeMessageBegin("getBlacklist", Thrift.MessageType.EXCEPTION, seqid);
			}
			result.write(output);
			output.writeMessageEnd();
			output.flush();
		});
	}
}

ExecutorServiceProcessor.prototype.process_getFragment = function (seqid, input, output) {
	var args = new ExecutorService_getFragment_args();
	args.read(input);
	input.readMessageEnd();
	if (this._handler.getFragment.length === 2) {
		Q.fcall(this._handler.getFragment, args.language, args.functions)
			.then(function (result) {
				var result = new ExecutorService_getFragment_result({ success: result });
				output.writeMessageBegin("getFragment", Thrift.MessageType.REPLY, seqid);
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			}, function (err) {
				var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
				output.writeMessageBegin("getFragment", Thrift.MessageType.EXCEPTION, seqid);
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			});
	} else {
		this._handler.getFragment(args.language, args.functions, function (err, result) {
			if (err == null) {
				var result = new ExecutorService_getFragment_result((err != null ? err : { success: result }));
				output.writeMessageBegin("getFragment", Thrift.MessageType.REPLY, seqid);
			} else {
				var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
				output.writeMessageBegin("getFragment", Thrift.MessageType.EXCEPTION, seqid);
			}
			result.write(output);
			output.writeMessageEnd();
			output.flush();
		});
	}
}

ExecutorServiceProcessor.prototype.process_execute = function (seqid, input, output) {
	var args = new ExecutorService_execute_args();
	args.read(input);
	input.readMessageEnd();
	if (this._handler.execute.length === 4) {
		Q.fcall(this._handler.execute, args.language, args.fragment, args.functions, args.testCases)
			.then(function (result) {
				var result = new ExecutorService_execute_result({ success: result });
				output.writeMessageBegin("execute", Thrift.MessageType.REPLY, seqid);
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			}, function (err) {
				var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
				output.writeMessageBegin("execute", Thrift.MessageType.EXCEPTION, seqid);
				result.write(output);
				output.writeMessageEnd();
				output.flush();
			});
	} else {
		this._handler.execute(args.language, args.fragment, args.functions, args.testCases, function (err, result) {
			if (err == null) {
				var result = new ExecutorService_execute_result((err != null ? err : { success: result }));
				output.writeMessageBegin("execute", Thrift.MessageType.REPLY, seqid);
			} else {
				var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
				output.writeMessageBegin("execute", Thrift.MessageType.EXCEPTION, seqid);
			}
			result.write(output);
			output.writeMessageEnd();
			output.flush();
		});
	}
}

